### ISSUE TITLE
Inheritance & JSON Property attribute

### ISSUE THREAD

**Issue by iarsslen** [francnuec/Neo4jClient.DataAnnotations#2]
The client doesn't support inheritance, by investigating the issue it seems that ResolveNames in EntityMemberInfo doesn't take in consideration the inherited fields and the relationship between them, thus it is always serialized using the property name instead of the JsonProperty Property name.

```csharp
class Parent {
[JsonProperty("id")]
public abstract string Id {get;set;}
}
class Child : Parent{
public override string Id {get;set;}
}
```
the result cypher query will always use the name "Id" instead of "id", this is due to the IsEquivalentTo function that compares the member declaring type with the reflection declaring type, this could be resolved be replacing:

```csharp
  public static bool IsEquivalentTo(this MemberInfo @this, string memberName, Type memberDeclaringType)
        {
            return @this?.Name == memberName && @this?.DeclaringType == memberDeclaringType;
        }
```

by 

```csharp
     public static bool IsEquivalentTo(this MemberInfo @this, string memberName, Type memberDeclaringType)
        {
            return @this?.Name == memberName && (@this?.DeclaringType?.IsAssignableFrom(memberDeclaringType) == true || memberDeclaringType.IsAssignableFrom(@this?.DeclaringType));

        }
```

**Comment by francnuec** [comment]
Thanks a lot for this. I have added tests for this scenario and merged your PR into the master branch.
