### ISSUE TITLE
Support IBoltGraphClient and BoltGraphClient

### ISSUE THREAD

**Issue by pcmantinker** [francnuec/Neo4jClient.DataAnnotations#5]
This library is very well written! I'm impressed with making interacting with Neo4j more similar to Entity Framework. Upon testing your Neo4j ASP.NET Core Identity implementation against Neo4j 4.0, I found I couldn't connect via the standard HTTP/REST protocol. That's where I discovered that the usage of IGraphClient was defined in this project. I cloned Neo4jClient.DataAnnotations and started trying to use the IBoltGraphClient in place of the IGraphClient, but they seem to not be completely interchangeable. Do you plan on adding support for IBoltGraphClient in the future?

**Comment by francnuec** [comment]
Thanks for the compliment.

Although, I haven't really tested the IBoltGraphClient, didn't even write any unit tests for it, but my understanding was that as long as the IGraphClient was supported, then they could easily be switched using dependency injection. Is there any specific error you encountered when you tried IBoltGraphClient?

**Comment by francnuec** [comment]
Just pushed an update to fix some issues with Bolt. I believe your Bolt client should work properly now.

**Comment by pcmantinker** [comment]
Thanks for getting this added. Sorry for such a late reply! The project I was working on was put on hold which is why I haven't had much time to reply. I hope to get time again soon to explore this library's features.
