### ISSUE TITLE
Objects traversing for given relation throws an InvalidOperationException

### ISSUE THREAD

**Issue by ashantiel** [francnuec/Neo4jClient.DataAnnotations#7]
Hi,

after our project growth a little, I found out a small issue with the not-so-specific scenario.

With a small graph in Neo4j like this:
<img width="711" alt="image" src="https://user-images.githubusercontent.com/2978911/78412665-7ace8600-7614-11ea-8a24-33f56837242e.png">

And code:

```
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Neo4jClient;
using Neo4jClient.Cypher;
using Neo4jClient.DataAnnotations;

namespace IssueRepro
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            var result = new Repository().Call();
            Console.WriteLine("Not here");
        }
    }
    public class ObjectA
    {
        public string Id => type.ToString();

        public string name { get; set; }

        public int type { get; set; }

        [Column("DEPENDS_ON")]
        public ICollection<ObjectB> ObjectsB { get; set; }

        [Column("DEPENDS_ON")]
        public ICollection<ObjectC> ObjectsC { get; set; }
    }

    public class ObjectB
    {
        public int sortOrder { get; set; }

        public string Id => value;
        public string value { get; set; }
        public string name { get; set; }


        [InverseProperty("ObjectsB")]
        public ICollection<ObjectA> ObjectsA { get; set; }

        [Column("DEPENDS_ON")]
        public ICollection<ObjectC> ObjectsC { get; set; }
    }

    public class ObjectC
    {
        public string Id { get; set; }

        public ObjectB NotB { get; set; }
        public ObjectA NotA { get; set; }

        [InverseProperty("ObjectsC")]
        public ICollection<ObjectA> ObjectsA { get; set; }

        [InverseProperty("ObjectsC")]
        public ICollection<ObjectB> ObjectsB { get; set; }

    }

    public class Repository : IDisposable
    {
        IGraphClient _graphClient;
        ICypherFluentQuery _query;
        public Repository()
        {
            _graphClient = new GraphClient(new Uri("http://localhost:7474/db/data"), "neo4j", "test");
            Connect();
            _query = _graphClient.WithAnnotations<AnnotationsContext>().Cypher;
        }

        public ICypherFluentQuery<ObjectA> Call()
        {
            var query = _query
                .Match(path => path.Pattern<ObjectA>("a"))
                .With("a")
                .Match(path => path.Pattern<ObjectA, ObjectB>("a", "b", RelationshipDirection.Outgoing))
                .Where((ObjectA objectA) => objectA.type == 0);
            Console.WriteLine(query.Query.DebugQueryText);
            return query.ReturnDistinct<ObjectA>("a");
        }

        public void Dispose()
        {
            _graphClient.Dispose();
        }

        private void Connect()
        {
            if (!_graphClient.IsConnected)
            {
                _graphClient.Connect();
            }
        }
    }
}
```

I'm getting the InvalidOperationException in Pattern.cs in line 900:
```
ColumnAttribute columnAttr = attrArray.Where(a => a != null
&& !string.IsNullOrWhiteSpace(((ColumnAttribute)a).Name))
.SingleOrDefault() as ColumnAttribute; //we expect just one attribute to be defined on the relationship. two would create confusion.
```
The `.SingleOrDefault()` is throwing this error. At first I thought it's just problem with bad reading of columns and `.FirstOrDefault() ` instead will do the work, but after a while I discovered what's the reason.
Using the attached graph, I just want to get `MATCH (ObjectA)-[:DEPENDS_ON]->(ObjectB)`. But because I have two fields (ObjectA, ObjectB) in ObjectC (which is not even taking any action here), traversing in your library is taking some misterious steps (which I still weren't able to reproduce) and in the end, it's trying to use ObjectA.ObjectC and ObjectB.ObjectC as properties in array `var attrArray = new[] { aAttr, bAttr };` to get column in the Pattern.cs:900 line.
This is because of those extra fields in the ObjectC, after removing them, everything works.
Do you have any idea why this behavior is here?
Why i.e. in Pattern.cs:1697 the code removes obvious properties and starts to traversing the rest?

**Comment by francnuec** [comment]
Hi, 

I'm sorry for the very late reply. Work is the culprit.

Looks strange. Off the top of my head, I can't think of a specific reason for this yet, but I would take a look at it hopefully soon and get back to you.

For your question on how ObjectC got involved? The reason should be because the library is trying to figure out the relationship between ObjectA and ObjectB in that query. The cyclic nature of the relationships of your nodes here might be a reason for that exception. So, I would say, due to the cyclic nature of the relationships, you should intentionally indicate the link between ObjectA and ObjectB in your pattern via a lambda function. That should solve it for now.

That is, instead of
`.Match(path => path.Pattern<ObjectA, ObjectB>("a", "b", RelationshipDirection.Outgoing))`

try,
`.Match(path => path.Pattern<ObjectA>(a => a.ObjectsB, "b", RelationshipDirection.Outgoing))`

I didn't use an editor to type the above code, so might be a little different when coding it, but the principle is same: this avoids any lookup by the library to figure out the relationship, especially since it's cyclic in nature.

Please try it and let me know your results.

**Comment by ashantiel** [comment]
Hi,

sorry for this pidgeon-style communication delay.

I made it work by applying very strict rules of [Column] and [InverseProperty] attributes on all entities for single graph.
So now each class for Node at the relationship start must have [Column] and [InverseProperty] attributes with collection of the other side of relationship AND each class for Node at the relationship end must have collection of other side with only [InverseProperty] attribute on it.

So for my case it would be:
```
public class ObjectA
    {
        public string Id => type.ToString();

        public string name { get; set; }

        public int type { get; set; }

        #region ObjectsForWhichRelationshipStartsHere

        [Column("DEPENDS_ON")]
        [InverseProperty("ObjectsA")]
        public ICollection<ObjectB> ObjectsB { get; set; }

        [Column("DEPENDS_ON")]
        [InverseProperty("ObjectsA")]
        public ICollection<ObjectC> ObjectsC { get; set; }

        #endregion
    }

    public class ObjectB
    {
        public int sortOrder { get; set; }

        public string Id => value;
        public string value { get; set; }
        public string name { get; set; }

        #region ObjectsFromWhichRelationshipEndsHere

        [InverseProperty("ObjectsB")]
        public ICollection<ObjectA> ObjectsA { get; set; }

        #endregion
        #region ObjectsForWhichRelationshipStartsHere

        [Column("DEPENDS_ON")]
        [InverseProperty("ObjectsB")]
        public ICollection<ObjectC> ObjectsC { get; set; }

        #endregion
    }

    public class ObjectC
    {
        public string Id { get; set; }

        public ObjectB NotB { get; set; }
        public ObjectA NotA { get; set; }

        #region ObjectsFromWhichRelationshipEndsHere

        [InverseProperty("ObjectsC")]
        public ICollection<ObjectA> ObjectsA { get; set; }

        [InverseProperty("ObjectsC")]
        public ICollection<ObjectB> ObjectsB { get; set; }

        #endregion
    }
```

This setup works for us pretty well. We have 60+ entities with a lot of relations between them, however all of them have single direction.

**Comment by francnuec** [comment]
Hi,

This is good. It is actually the same as using the lambda functions as I suggested. However, this is better, as the attributes declare the relationships once and for all. 

I'm glad it works for you now. I will be closing this.
